model:
  default: upstage/solar-pro4:free
  provider: nous
  base_url: https://inference-api.nousresearch.com/v1
skills:
  write_approval: true
command_allowlist:
  - script execution via -e/-c flag
  - execute_code
agent:
  max_turns: 150
_config_version: 46
platform_toolsets:
  cli:
    - clarify
    - connections
    - cronjob
    - file
    - memory
    - session_search
    - skills
    - terminal
    - todo
    - web
known_plugin_toolsets:
  cli:
    - a2a
    - spotify
known_builtin_toolsets:
  cli:
    - browser
    - clarify
    - code_execution
    - computer_use
    - connections
    - context_engine
    - cronjob
    - delegation
    - discord
    - discord_admin
    - file
    - homeassistant
    - image_gen
    - kanban
    - memory
    - session_search
    - skills
    - spotify
    - stt
    - terminal
    - todo
    - tts
    - video
    - video_gen
    - vision
    - web
    - x_search
    - yuanbao
